apiVersion: v1
kind: Service
metadata:
    name: timeserver
spec:
    replicas: 3
    selector: 
        matchLabels: 
            pod: timeserver-pod
    template:
        metadata:
            matchLabels:
                pod: timeserver-pod
        spec:
            containers:
            - name : timeserver-container
              image: docker.io/wdenniss/timeserver:1 #using an open source image from docker hub

